version: "3.9"

services:

  database:
    build: 
      context: ./images/sql
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./images/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    hostname: timetable.mirea
    build:
      context: ./
      dockerfile: images/python/Dockerfile.server
    command: python3 timetable/manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespostgres
      DB_HOST: database
      DB_PORT: 5432
    restart: unless-stopped
    depends_on:
      - database

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - server