version: "3.9"

services:

  database:
    build: 
      context: ./images/sql
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: TimeTableDB
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: password
      DB_HOST: database
      DB_PORT: 5432
    volumes:
      - ./images/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d TimeTableDB -U denis"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    hostname: timetable.mirea
    build:
      context: ./
      dockerfile: images/python/Dockerfile.server
    restart: unless-stopped
    # Временно
    volumes:
      - ./src:/server
    # Временно
    command: >
      sh -c "python3 timetable/manage.py migrate &&
             python3 timetable/manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: TimeTableDB
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: password
      DB_HOST: database
      DB_PORT: 5432
    healthcheck:
      test: curl -sS http://0.0.0.0:8000 || echo 1
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      database:
        condition: service_healthy
      server:
        condition: service_healthy