FROM ubuntu:22.10
ENV PIP_ROOT_USER_ACTION=ignore
COPY ./images/server/requirements.txt /tmp/
RUN apt-get -qq update && apt-get -qq install python3-pip && \
    pip3 install pip --upgrade && pip install -r /tmp/requirements.txt && mkdir /server/
COPY ./images/server/server /server/
WORKDIR /server
CMD python3 main.py
HEALTHCHECK --interval=10s --timeout=100s --retries=30 CMD ls success || exit 1