FROM ubuntu:22.10
ENV PIP_ROOT_USER_ACTION=ignore
COPY ./images/django/requirements.txt /tmp/
RUN apt-get -qq update && apt-get -qq install python3-pip && \
    pip3 install pip --upgrade && pip install -r /tmp/requirements.txt && mkdir /server/
#COPY ./images/server/server /server/
WORKDIR /server
