# Generated by Django 3.2 on 2022-12-02 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSchedule',
            fields=[
                ('subject_number', models.IntegerField(primary_key=True, serialize=False)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_of_course', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id_of_degree', models.AutoField(primary_key=True, serialize=False)),
                ('degree_of_study', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id_of_the_institute', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_the_institute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id_lecturer', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=20)),
                ('id_institute', models.IntegerField(blank=True, null=True)),
                ('id_of_course', models.IntegerField()),
                ('id_degree', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id_to_group', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_to_number', models.IntegerField()),
                ('id_lectur', models.IntegerField(blank=True, null=True)),
                ('subject_title', models.CharField(max_length=500)),
                ('auditorium', models.CharField(blank=True, max_length=500, null=True)),
                ('day_week', models.IntegerField()),
                ('type_of_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_group', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
