# Generated by Django 3.2 on 2022-12-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callschedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studygroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'managed': False},
        ),
    ]
